DROP TABLE IF EXISTS FACT_MATCHES;
DROP TABLE IF EXISTS DIM_PLAYER;
DROP TABLE IF EXISTS DIM_TOURNEY;
DROP TABLE IF EXISTS DIM_SCORE;
DROP TABLE IF EXISTS DIM_STATS;
DROP TABLE IF EXISTS DIM_TIME;

CREATE TABLE FACT_MATCHES 
(
	[Date] int NOT NULL, 
	[WinnerID] int NOT NULL, 
	[LoserID] int NOT NULL, 
	[TourneyID] int NOT NULL,
	[WinnerStatsID] int NOT NULL, 
	[LoserStatsID] int NOT NULL, 
	[ScoreID] int NOT NULL, 
	[Round] varchar(4) NULL, 
	[Duration] int NULL, 
	[BestOf] int NULL
);
CREATE TABLE DIM_PLAYER 
(
	[PlayerID] int IDENTITY NOT NULL, 
	[PlayerName] varchar(50) NOT NULL, 
	[DominantHand] char(1) NULL, 
	[Height] int NULL, 
	[Age] int NULL, 
	[Rank] int NULL, 
	[Nationality] char(3) NULL
);
CREATE TABLE DIM_TIME 
(
	[PK_TIME] int IDENTITY NOT NULL, 
	[Year] int NOT NULL, 
	[Month] int NOT NULL, 
	[Day] int NOT NULL
);
CREATE TABLE DIM_TOURNEY 
(
	[TourneyID] int IDENTITY NOT NULL, 
	[TourneyName] varchar(50) NOT NULL, 
	[TourneyLevel] char(1) NULL, 
	[DrawSize] int NULL, 
	[Surface] varchar(10) NULL
);
CREATE TABLE DIM_STATS 
(
	[StatsID] int IDENTITY NOT NULL, 
	[Aces] int NULL, 
	[BreakpointsWon] int NULL, 
	[BreakpointsFaced] int NULL, 
	[FirstServeWon] int NULL, 
	[DoubleFaults] int NULL
);
CREATE TABLE DIM_SCORE 
(
	[ScoreID] int IDENTITY NOT NULL, 
	[Set1] varchar(10) NULL, 
	[Set2] varchar(10) NULL, 
	[Set3] varchar(10) NULL, 
	[Set4] varchar(10) NULL, 
	[Set5] varchar(10) NULL
);
ALTER TABLE DIM_SCORE ADD CONSTRAINT pk_score_id PRIMARY KEY (ScoreID);
ALTER TABLE DIM_TOURNEY ADD CONSTRAINT pk_tourney_id PRIMARY KEY (TourneyID);
ALTER TABLE DIM_PLAYER ADD CONSTRAINT pk_player_id PRIMARY KEY (PlayerID);
ALTER TABLE DIM_STATS ADD CONSTRAINT pk_stats_id PRIMARY KEY (StatsID);
ALTER TABLE DIM_TIME ADD CONSTRAINT pk_time_id PRIMARY KEY (PK_TIME);
ALTER TABLE FACT_MATCHES ADD CONSTRAINT fk_fm_scoreID FOREIGN KEY (ScoreID) REFERENCES DIM_SCORE (ScoreID);
ALTER TABLE FACT_MATCHES ADD CONSTRAINT fk_fm_winnerID FOREIGN KEY (WinnerID) REFERENCES DIM_PLAYER (PlayerID);
ALTER TABLE FACT_MATCHES ADD CONSTRAINT fk_fm_loserID FOREIGN KEY (LoserID) REFERENCES DIM_PLAYER (PlayerID);
ALTER TABLE FACT_MATCHES ADD CONSTRAINT fk_fm_wStatsID FOREIGN KEY (WinnerStatsID) REFERENCES DIM_STATS (StatsID);
ALTER TABLE FACT_MATCHES ADD CONSTRAINT fk_fm_lStatsID FOREIGN KEY (LoserStatsID) REFERENCES DIM_STATS (StatsID);
ALTER TABLE FACT_MATCHES ADD CONSTRAINT fk_fm_time FOREIGN KEY ([Date]) REFERENCES DIM_TIME (PK_TIME);
ALTER TABLE FACT_MATCHES ADD CONSTRAINT fk_fm_tourneyID FOREIGN KEY (TourneyID) REFERENCES DIM_TOURNEY (TourneyID);
